### ISSUE TITLE
Conflict found with Dectorio

### ISSUE THREAD

**Issue by anonhostpi** [dvilker/FactorioRailLogisticsDispatcher#33]
This error occurs when loading this mod and dectorio at the same time:

![image](https://github.com/user-attachments/assets/eafb9f43-818b-4a20-8506-92444810b7ac)

No other mod was loaded. Not even space age or quality:

<img width="750" alt="image" src="https://github.com/user-attachments/assets/f944c71e-a1a7-4c04-bec5-807c3867f308">

**Comment by anonhostpi** [comment]
I have opened this issue in both repositories: https://github.com/jpanther/dectorio/issues/260

**Comment by ourpxi** [comment]
Currently playing with dectorio, rail disparcher and about 50 more mods without any issue at all. apart from skill issue

**Comment by anonhostpi** [comment]
Well, in that case:

Factorio 2, Windows 11

**Comment by dvilker** [comment]
Fixed in 2.0.20
