### ISSUE TITLE
Remove/make configurable train names

### ISSUE THREAD

**Issue by modo-lv** [dvilker/FactorioRailLogisticsDispatcher#4]
The white text showing what depot station the train is coming from has several issues:
* It cannot be switched off.
* When the station name changes, it does not replace the old one, but writes over it (see screenshot).
* It does not correctly handle rich text station names (see screenshot).

I suggest enabling/disabling it with a setting, at least.

![image](https://user-images.githubusercontent.com/731551/206928352-ebc6eaf8-85ac-4194-9a8c-372c57e2d8c1.png)

**Comment by tburrows13** [comment]
Sadly LuaRendering can't do richtext icons https://forums.factorio.com/67264 :( Space Exploration's spaceships suffer from the same problem if you use richtext icons in them.

**Comment by modo-lv** [comment]
As long as there's an option to turn it off.

**Comment by dvilker** [comment]
Train signatures were needed for debugging and accidentally sneaked into the release. I will remove them in the next update.
Thank you

**Comment by dvilker** [comment]
Removed in 0.0.17

On existing trains, it will take a little time for the signatures to disappear.
