### ISSUE TITLE
Network `0` means "all networks"?

### ISSUE THREAD

**Issue by modo-lv** [dvilker/FactorioRailLogisticsDispatcher#6]
While looking at the code for #5, I noticed that network `0` seems to be matching all networks. This could be misleading, because according to the mod description (and bitmasking as such), you need to combine network numbers to get more than one. `0` should not match any networks. Or else there should be a warning next to the input field, that `0` means all networks, instead of none.

**Comment by dvilker** [comment]
Accepted, thanks. In the next update, 0 will mean - no networks, and -1 - all networks.
