### ISSUE TITLE
More than 32 networks

### ISSUE THREAD

**Issue by DarkShadow44** [dvilker/FactorioRailLogisticsDispatcher#9]
Especially for SpaceExploration, you can have more than 32 surfaces, which would need more than 32 networks.
Maybe we can have some other network identifier for surfaces? [Cybersyn](https://mods.factorio.com/mod/cybersyn) for example groups first by a virtual signal that you can configure, then by network id.

Other idea would be grouping by surface, although with SpaceExplorations space elevator you can have two surfaces as one train network. Therefore I'd prefer a different option to keep that open for future support. :smile:

**Comment by dvilker** [comment]
Good day. Thanks for your interest in my mod. At the moment there is no space elevator support at all. An elevator destroys a train on one surface and creates it on another. In fact, it will already be another train and delivery will be lost.

In this case, the mod processes each surface separately. Each surface has its own set of net masks.

I hope I get my hands on it to make support for the space elevator.

Have a good game!)

**Comment by DarkShadow44** [comment]
Ah, in this case this probably isn't an issue, didn't know surfaces were already separate! regarding space elevator support, you can look at how Cybersyn does it if you want, it's also open source.
